INSERT INTO bookcamp.author (name,surname,image,bio)
Values  ('Suzanne ','Collins','images/authors/suzannecollins.jpg', 'Since 1991, Suzanne Collins has been busy writing for children’s television. She has worked on the staffs of several Nickelodeon shows, including the Emmy-nominated hit Clarissa Explains it All and The Mystery Files of Shelby Woo. For preschool viewers, she penned multiple stories for the Emmy-nominated Little Bear and Oswald. She also co-wrote the critically acclaimed Rankin/Bass Christmas special, Santa, Baby! Most recently she was the Head Writer for Scholastic Entertainment’s Clifford’s Puppy Days.
'),
		('J.K. ','Rowling','images/authors/jkrowling.jpg','Although she writes under the pen name J.K. Rowling, pronounced like rolling, her name when her first Harry Potter book was published was simply Joanne Rowling. Anticipating that the target audience of young boys might not want to read a book written by a woman, her publishers demanded that she use two initials, rather than her full name. As she had no middle name, she chose K as the second initial of her pen name, from her paternal grandmother Kathleen Ada Bulgen Rowling. She calls herself Jo and has said, "No one ever called me Joanne when I was young, unless they were angry." '
),
        ('Harper ','Lee','images/authors/harperlee.jpg','Harper Lee, known as Nelle, was born in the Alabama town of Monroeville, the youngest of four children of Amasa Coleman Lee and Frances Cunningham Finch Lee. Her father, a former newspaper editor and proprietor, was a lawyer who served on the state legislature from 1926 to 1938. As a child, Lee was a tomboy and a precocious reader, and enjoyed the friendship of her schoolmate and neighbor, the young Truman Capote.'
),
        ('Jane ','Austen','images/authors/janeausten.jpg','Jane Austen was an English novelist whose works of romantic fiction, set among the landed gentry, earned her a place as one of the most widely read writers in English literature, her realism and biting social commentary cementing her historical importance among scholars and critics.'
),
        ('Stephenie ','Meyer','images/authors/stepheniemeyer.jpg','I was born in Connecticut in 1973, during a brief blip in my familys otherwise western U.S. existence. We were settled in Phoenix by the time I was four, and I think of myself as a native. The unusual spelling of my name was a gift from my father, Stephen (+ ie = me). Though I have had my name spelled wrong on pretty much everything my entire life long, I must admit that it makes it easier to google myself now.'
),
        ('C.S. ','Lewis','images/authors/cslewis.jpg','CLIVE STAPLES LEWIS (1898–1963) was one of the intellectual giants of the twentieth century and arguably one of the most influential writers of his day. He was a Fellow and Tutor in English Literature at Oxford University until 1954. He was unanimously elected to the Chair of Medieval and Renaissance Literature at Cambridge University, a position he held until his retirement. He wrote more than thirty books, allowing him to reach a vast audience, and his works continue to attract thousands of new readers every year. '
),
        ('Markus ','Zusak','images/authors/markuszusak.jpg','Markus Zusak was born in 1975 and is the author of five books, including the international bestseller, The Book Thief , which is translated into more than forty languages. First released in 2005, The Book Thief has spent more than a decade on the New York Times bestseller list, and still remains there to this day.'
),
        ('George ','Orwell','images/authors/georgeorwell.jpg','Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism.'
),
        ('Margaret ','Mitchell','images/authors/margaretmitchell.jpg','Margaret Munnerlyn Mitchell, popularly known as Margaret Mitchell, was an American author, who won the Pulitzer Prize in 1937 for her novel, Gone with the Wind, published in 1936. The novel is one of the most popular books of all time, selling more than 28 million copies. An American film adaptation, released in 1939, became the highest-grossing film in the history of Hollywood, and received a record-breaking number of Academy Awards.'
),
        ('Shel ','Silverstein','images/authors/shelsilverstein.jpg','Shel Silverstein was the author-artist of many beloved books of prose and poetry. He was a cartoonist, playwright, poet, performer, recording artist, and Grammy-winning, Oscar-nominated songwriter.'
),
        ('Douglas ','Adams','images/authors/douglasadams.jpg','Douglas Noël Adams was an English author, comic radio dramatist, and musician. He is best known as the author of the Hitchhikers Guide to the Galaxy series. Hitchhikers began on radio, and developed into a "trilogy" of five books (which sold more than fifteen million copies during his lifetime) as well as a television series, a comic book series, a computer game, and a feature film that was completed after Adams death.'
),
        ('John ','Green','images/authors/johngreen.jpg','John Greens first novel, Looking for Alaska, won the 2006 Michael L. Printz Award presented by the American Library Association. His second novel, An Abundance of Katherines, was a 2007 Michael L. Printz Award Honor Book and a finalist for the Los Angeles Times Book Prize. His next novel, Paper Towns, is a New York Times bestseller and won the Edgar Allen Poe Award for Best YA Mystery.'
),
        ('J.R.R. ','Tolkien','images/authors/tolkien.jpg','John Ronald Reuel Tolkien, CBE, was an English writer, poet, WWI veteran (a First Lieutenant in the Lancashire Fusiliers, British Army), philologist, and university professor, best known as the author of the high fantasy classic works The Hobbit and The Lord of the Rings .'
),
        ('Emily ','Brontë','images/authors/emilybronte.jpg','Emily Jane Brontë was a British novelist and poet, now best remembered for her only novel Wuthering Heights, a classic of English literature. Emily was the second eldest of the three surviving Brontë sisters, being younger than Charlotte Brontë and older than Anne Brontë. She published under the masculine pen name Ellis Bell.'
),
        ('Dan ','Brown','images/authors/danbrown.jpg','Dan Brown is the author of numerous #1 bestselling novels, including The Da Vinci Code, which has become one of the best selling novels of all time as well as the subject of intellectual debate among readers and scholars. Brown’s novels are published in 52 languages around the world with 200 million copies in print.'
),
        ('Arthur ','Golden','images/authors/arthurgolden.jpg','Arthur Golden was born in Chattanooga, Tennessee, and was educated at Harvard College, where he received a degree in art history, specializing in Japanese art. In 1980 he earned an M.A. in Japanese history from Columbia University, where he also learned Mandarin Chinese. Following a summer in Beijing University, he worked in Tokyo, and, after returning to the United States, earned an M.A. in English from Boston University. He resides in Brookline, Massachusetts, with his wife and two children. '
),
        ('Lewis ','Carroll','images/authors/lewiscarroll.jpg','The Reverend Charles Lutwidge Dodgson, better known by the pen name Lewis Carroll, was an English author, mathematician, logician, Anglican clergyman and photographer.'
),
        ('Victor ','Hugo','images/authors/victorhugo.jpg','Victor-Marie Hugo was a French poet, playwright, novelist, essayist, visual artist, statesman, human rights campaigner, and perhaps the most influential exponent of the Romantic movement in France.'
),
        ('William ','Shakespeare','images/authors/williamshakespeare.jpg','William Shakespeare (baptised 26 April 1564) was an English poet and playwright, widely regarded as the greatest writer in the English language and the worlds pre-eminent dramatist. He is often called Englands national poet and the "Bard of Avon" (or simply "The Bard"). His surviving works consist of 38 plays, 154 sonnets, two long narrative poems, and several other poems. His plays have been translated into every major living language, and are performed more often than those of any other playwright.'
),
        ('Veronica ', 'Roth','images/authors/veronicaroth.jpg','Veronica Roth is from a Chicago suburb. She studied creative writing at Northwestern University, and wrote DIVERGENT (Katherine Tegen Books, May 2011) and INSURGENT (May 2012). The third and final book in The Divergent Trilogy, ALLEGIANT, will come out on October 22, 2013. In the meantime she will spend endless hours browsing Wikipedia in her pajamas as she eats corn flakes. (Or some other kind of bland breakfast cereal.)');