insert into bookcamp.user (username, surname, name, age, sex)
values ('agnavag', 'Agnadopoulos', 'Vaggelis', 30, 'm'),
	   ('aididia', 'Aidinis', 'Diamantis', 25, 'm'),
       ('alexpyr', 'Alexopoulos', 'Pyrros', 20, 'm'),
       ('anakai', 'Anastasaki', 'Kaiti', 23, 'f'),
       ('andrini', 'Andrikopoulos', 'Nikolaos', 32, 'm'),
       ('arvagg', 'Aravanitis', 'Aggelos', 45, 'm'),
       ('barli', 'Barbarousi', 'Lida', 18, 'f'),
       ('bikari', 'Bikendiou', 'Aristotelis', 28, 'm'),
       ('bousan', 'Bousouras', 'Andreas', 52, 'm'),
       ('georei', 'Georgopoulou', 'Eirini', 35, 'f'),
       ('gkouva', 'Gkouzia', 'Balia', 31, 'f'),
       ('gkremgeo', 'Gkremouti', 'Georgia', 25, 'f'),
       ('gkriel', 'Gkriva', 'Elli', 20, 'f'),
       ('dmpaly', 'Dampasina', 'Lydia', 24, 'f'),
       ('delini', 'Deligiannis', 'Nikos', 30, 'm'),
       ('dengia', 'Dendrinos', 'Giannis', 20, 'm'),
       ('dimibi', 'Dimitrakoulis', 'Bironas', 40, 'm'),
       ('dibeu', 'Dibari', 'Eva', 20, 'f'),
       ('drama', 'Drakouli', 'Marina', 30, 'f'),
       ('zaxma', 'Zaxaroudakis', 'Manolis', 25, 'm'),
       ('kalizi', 'Kalliga', 'Lizi', 20, 'f');